-- LIHAT DATABASES
SHOW DATABASES;
-- MENGGUNAKAN DATABASES mysql
USE mysql;
-- MELIHAT ISI TABEL DALAM DB mysql
SHOW TABLES;
-- MELIHAT DESKRIPSI DARI TABLE user
DESCRIBE user;
-- AMBIL ISI DARI KOLOM HOST. USER, PASSWORD
SELECT Host, User, Password FROM user;